<?php // this is an autogenerated file - do not edit (created Mon, 21 Feb 2011 17:04:17 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'splitout\\model\\abstractuser' => '/model/AbstractUser.php',
            'splitout\\model\\comment' => '/model/Comment.php',
            'splitout\\model\\event' => '/model/Event.php',
            'splitout\\model\\eventexception' => '/model/Event.php',
            'splitout\\model\\session' => '/model/Session.php',
            'splitout\\model\\sessionexception' => '/model/Session.php',
            'splitout\\model\\tobeannounceduser' => '/model/ToBeAnnouncedUser.php',
            'splitout\\model\\user' => '/model/User.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
