<?php // this is an autogenerated file - do not edit (created Tue, 22 Feb 2011 11:31:59 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'splitout\\application\\finder' => '/application/Finder.php',
            'splitout\\application\\helper' => '/application/Helper.php',
            'splitout\\application\\logincontroller' => '/application/LoginController.php',
            'splitout\\framework\\controller' => '/framework/Controller.php',
            'splitout\\framework\\request' => '/framework/Request.php',
            'splitout\\model\\abstractuser' => '/model/AbstractUser.php',
            'splitout\\model\\comment' => '/model/Comment.php',
            'splitout\\model\\event' => '/model/Event.php',
            'splitout\\model\\eventexception' => '/model/Event.php',
            'splitout\\model\\presenter' => '/model/Presenter.php',
            'splitout\\model\\session' => '/model/Session.php',
            'splitout\\model\\sessionexception' => '/model/Session.php',
            'splitout\\model\\tobeannounceduser' => '/model/ToBeAnnouncedUser.php',
            'splitout\\model\\user' => '/model/User.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
