<?php // this is an autogenerated file - do not edit (created Tue, 22 Feb 2011 16:32:52 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'splitout\\application\\ajaxworkflow' => '/application/AjaxWorkflow.php',
            'splitout\\application\\authentication' => '/application/Authentication.php',
            'splitout\\application\\errorview' => '/application/ErrorView.php',
            'splitout\\application\\factory' => '/application/Factory.php',
            'splitout\\application\\factoryexception' => '/application/Factory.php',
            'splitout\\application\\finder' => '/application/Finder.php',
            'splitout\\application\\helper' => '/application/Helper.php',
            'splitout\\application\\logincontroller' => '/application/LoginController.php',
            'splitout\\application\\pageworkflow' => '/application/PageWorkflow.php',
            'splitout\\application\\staticpageview' => '/application/StaticPageView.php',
            'splitout\\application\\successview' => '/application/SuccessView.php',
            'splitout\\framework\\controller' => '/framework/Controller.php',
            'splitout\\framework\\request' => '/framework/Request.php',
            'splitout\\framework\\response' => '/framework/Response.php',
            'splitout\\framework\\view' => '/framework/View.php',
            'splitout\\framework\\workflow' => '/framework/Workflow.php',
            'splitout\\framework\\workflowexception' => '/framework/Workflow.php',
            'splitout\\model\\abstractuser' => '/model/AbstractUser.php',
            'splitout\\model\\comment' => '/model/Comment.php',
            'splitout\\model\\event' => '/model/Event.php',
            'splitout\\model\\eventexception' => '/model/Event.php',
            'splitout\\model\\presenter' => '/model/Presenter.php',
            'splitout\\model\\session' => '/model/Session.php',
            'splitout\\model\\sessionexception' => '/model/Session.php',
            'splitout\\model\\tobeannounceduser' => '/model/ToBeAnnouncedUser.php',
            'splitout\\model\\user' => '/model/User.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
